{% set name = "autodataman" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmecmetrics/autodataman/archive/refs/tags/{{ version }}.tar.gz
  sha256: 3d858c6bdfe624d01e23c8f322bfb8ea83418322f9c1d7118047246cd6f902b8

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - autodataman = autodataman.autodataman:main
    - adm = autodataman.autodataman:main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - requests

test:
  requires:
    - python {{ python_min }}
  imports:
    - autodataman
  commands:
    - autodataman --help

about:
  home: https://github.com/cmecmetrics/autodataman
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Autodataman
  description: |
    The autodataman tool is intended to be a very lightweight climate data database and data distribution engine.
  doc_url: https://github.com/cmecmetrics/autodataman/tree/ao_python#readme
  dev_url: https://github.com/cmecmetrics/autodataman

extra:
  recipe-maintainers:
    - acordonez
    - paullric
